name: BusBooking

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          cd ~/project/BusBooking/BusBooking
          docker compose build

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy containers
        run: |
          cd ~/project/BusBooking/BusBooking
          docker compose up -d
          docker ps
  show-info:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Show log
        run: |
          docker logs --tail=50 frontend || true
          docker logs --tail=50 backend || true

