name: BusBooking

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy with Docker Compose
        run: |
          cd ~/project/BusBooking/BusBooking
          git pull
          docker compose up -d --build
